<?php

/**
 * @file
 * Contains foxmodule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function foxmodule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the foxmodule module.
    case 'help.page.foxmodule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('fox module with lots of yiff') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function foxmodule_theme() {
  return [
    'foxmodule' => [
      'template' => 'foxmodule',
      'render element' => 'children',
    ],
  ];
}
